Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/bionic64"
   config.vm.network "private_network", type: "dhcp",
      name: "vboxnet0" 
   config.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = "2"
   end
end
